### ISSUE TITLE
What additional features does it have over original repo?

### ISSUE THREAD

**Issue by nitinmukesh** [JackismyShephard/ultimate-rvc#58]

**Comment by JackismyShephard** [comment]
Thank you for asking. 

I am in the process of updating the README, but I still have not gotten around to listing the new features which this app offers. At a glance, here are some of the new features:
* Easy and automated setup using launcher scripts for both windows and debian-based linux systems
* Caching system which saves intermediate audio files as needed, thereby reducing inference time as much as possible. For example, if song A has already been converted using model B and now you want to convert song A using model C, then vocal extraction can can be skipped and inference time reduced drastically (from 1.5 minutes to 20 seconds on my setup)
* Ability to listen to intermediate audio files in the UI. This is useful for getting an idea of what is happening in each step of song cover generation pipeline
* A "multi-step" song cover generation tab: here you can try out each step of the song cover generation in isolation. For example, if you already have extracted vocals available and only want to convert these using your voice model, then you can do that here. Besides, this tab is useful for experimenting with settings for each step of the song cover generation pipeline
* An overhaul of the song input component for the song cover generation pipeline. Now cached input songs can be selected from a dropdown, so that you don't have to supply the Youtube link of a song, each time you want to convert it. 
* A new "manage models" tab, which collects and revamps all existing functionality for managing voice models, as well as adds some new features, such as the ability to delete existing models
* A "manage audio", which allows you to to interact with all audio generated by the app. Currently, this tab supports deleting audio files.
* Lots of visual and performance improvements resulting from updating from Gradio 3 to Gradio 4 and from python 3.9 to python 3.10

**Comment by JackismyShephard** [comment]
In addition, many new features are under development, some of these include:
* Revamp of vocal extraction functionality using https://github.com/karaokenerds/python-audio-separator. My hope is that it will be possible to compose extraction models as desired and choose ideal parameters for each in the UI, while still keeping suitable defaults for the average user, who does not want to be burdened with too much complexity
* Improvements to vocal conversion step using latest VC code from https://github.com/IAHispano/Applio and https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI
* The ability to do batch conversion jobs in the app
* Support for training your own models in the app
* TTS using RVC
* Support for real-time (i.e. streaming) voice conversion

**Comment by nitinmukesh** [comment]
@JackismyShephard 

Appreciate your response. Thank you for your work.
I am gonna try this and create video for my viewers.

**Comment by JackismyShephard** [comment]
@nitinmukesh that sounds great. Any exposure is greatly appreciated. Feel free to share a link to the video once it is up 😊
